// X sub-agent: Engagement Responder — Tier 2.5
// Crafts replies, quote tweets, and engagement responses for X.
// Wired to X API v2 for fetching mentions and posting replies.

import { Agent } from "@mastra/core/agent";
import { createTool } from "@mastra/core/tools";
import { z } from "zod";
import { wrapToolHandler, validateReply, incrementReplyRate } from "@/agents/general";
import { modelConfig } from "@/agents/platforms/model-config";
import {
  getUserMentions,
  postTweet,
  type XOAuthCredentials,
  type XMentionsResponse,
} from "@/lib/x-api";

// ── Fetch X Mentions Tool ───────────────────────────────────

const fetchMentions = createTool({
  id: "fetchMentions",
  description: "Fetch recent @mentions for the authenticated X user via API v2",
  inputSchema: z.object({
    bearerToken: z.string().describe("X API Bearer Token"),
    userId: z.string().describe("X user ID to fetch mentions for"),
    limit: z.number().optional().describe("Max mentions to return (5-100)"),
  }),
  execute: async (executionContext) => {
    const { bearerToken, userId, limit } = executionContext.context;
    const wrappedFn = wrapToolHandler(
      async (input: { bearerToken: string; userId: string; limit?: number }) => {
        const mentions: XMentionsResponse = await getUserMentions(
          input.bearerToken,
          input.userId,
          input.limit ?? 20,
        );
        return {
          mentions: (mentions.data ?? []).map((tweet) => ({
            tweetId: tweet.id,
            text: tweet.text,
            authorId: tweet.author_id,
            createdAt: tweet.created_at,
            metrics: tweet.public_metrics,
            authorInfo: mentions.includes?.users?.find((u) => u.id === tweet.author_id),
          })),
          count: mentions.meta?.result_count ?? 0,
        };
      },
      { agentName: "x-engagement-responder", toolName: "fetchMentions" },
    );
    return wrappedFn({ bearerToken, userId, limit });
  },
});

// ── Craft & Post Reply Tool ─────────────────────────────────

const craftReply = createTool({
  id: "craftReply",
  description: "Craft a brand-voice reply to a tweet, validate via safety checks, and optionally post it",
  inputSchema: z.object({
    originalTweet: z.string().describe("The tweet text to reply to"),
    context: z.string().optional().describe("Additional context about the conversation or brand"),
    replyStyle: z.enum(["witty", "helpful", "insightful", "empathetic"]).optional().describe("Desired reply style"),
    replyText: z.string().optional().describe("Pre-crafted reply text (if already generated by agent)"),
    // Posting params (optional — if provided, will post after validation)
    post: z.boolean().optional().describe("Whether to actually post the reply"),
    inReplyToTweetId: z.string().optional().describe("Tweet ID to reply to"),
    organizationId: z.string().optional().describe("Organization ID for rate limiting"),
    brandVoice: z.string().optional().describe("Brand voice for safety checks"),
    oauthCredentials: z.object({
      apiKey: z.string(),
      apiSecret: z.string(),
      accessToken: z.string(),
      accessTokenSecret: z.string(),
    }).optional().describe("X OAuth 1.0a credentials for posting"),
  }),
  execute: async (executionContext) => {
    const ctx = executionContext.context;
    const wrappedFn = wrapToolHandler(
      async (input: typeof ctx) => {
        const reply = input.replyText ?? "";

        // Validate reply through safety checks if we have org context
        if (input.organizationId && reply) {
          const validation = await validateReply(
            reply,
            "x",
            input.organizationId,
            input.brandVoice,
          );

          if (!validation.approved) {
            return {
              originalTweet: input.originalTweet,
              reply,
              posted: false,
              safety: validation,
              error: `Reply blocked by safety: ${validation.reasons.join("; ")}`,
            };
          }

          // Post if requested and validated
          if (input.post && input.oauthCredentials && input.inReplyToTweetId) {
            const creds: XOAuthCredentials = input.oauthCredentials;
            const result = await postTweet(reply, creds, input.inReplyToTweetId);
            await incrementReplyRate("x", input.organizationId);
            return {
              originalTweet: input.originalTweet,
              reply,
              posted: true,
              tweetId: result.data.id,
              safety: validation,
            };
          }

          return {
            originalTweet: input.originalTweet,
            reply,
            posted: false,
            safety: validation,
            replyStyle: input.replyStyle ?? "helpful",
          };
        }

        return {
          originalTweet: input.originalTweet,
          reply,
          posted: false,
          replyStyle: input.replyStyle ?? "helpful",
          context: input.context ?? "",
        };
      },
      { agentName: "x-engagement-responder", toolName: "craftReply" },
    );
    return wrappedFn(ctx);
  },
});

export const engagementResponderAgent = new Agent({
  name: "x-engagement-responder",
  instructions: `You are an Engagement Responder sub-agent for the X (Twitter) platform.

Your job is to craft engaging responses to interactions:
- Replies to mentions and comments
- Quote tweets that add value
- Responses to trending conversations
- Community engagement in threads

Use fetchMentions to get recent @mentions, then craftReply to compose and optionally post replies.
All replies are validated through safety checks (profanity, brand voice, rate limits) before posting.

Maintain brand voice while being authentic and conversational.
Avoid controversy. Prioritize helpful, witty, or insightful responses.
Note: programmatic replies only succeed if the original author @mentioned you or quoted your post.`,
  model: modelConfig.tier25,
  tools: { fetchMentions, craftReply },
});
